### PR TITLE
format scenario data for p4b input

### PR DESCRIPTION
**Pull request by jacobvjk**
depends on: https://github.com/RMI-PACTA/pacta.scenario.data.preparation/pull/59

- gains script `format_scenarios_for_p4b.R` which formats the prepared scenarios for use in P4B
- selects the relevant scenarios based on inherited `scenarios_to_include` from config, which is determined by the `config_name` (i.e. the timestamp of the data preparation)
- follows the logic used in https://github.com/RMI-PACTA/workflow.data.preparation/blob/9beb13c4bdce7937bcfe327e8e12d75599090dcc/run_pacta_data_preparation.R#L267 as much as possible
- storing the files `p4b_scenarios_YYYY.csv` and `p4b_ei_scenarios_YYYY.csv` in the output_path does not interfere with workflow.data.preparation, because scenario files in that workflow are specifically targeted following the `source_YYYY.csv` naming convention, see https://github.com/RMI-PACTA/workflow.data.preparation/blob/9beb13c4bdce7937bcfe327e8e12d75599090dcc/run_pacta_data_preparation.R#L142 specifying scenario filenames in the config as shown here: https://github.com/RMI-PACTA/workflow.data.preparation/blob/9beb13c4bdce7937bcfe327e8e12d75599090dcc/config.yml#L176
- uses a common `final_year` as a cutoff for the scenarios. `final_year` is determined as the maximum year across featured scenario sources. For the preparation of 2023 scenarios, this is 2050. Values post 2050 seem a bit uncertain in GECO, so this was determined as the best way forward for now.

NOTE:
- The validation could be improved

### CODE REVIEW

**Comment by jdhoffa** [comment]
I agree that we should avoid polluting `main.R` too much, but it's fine to get the logic in there while in draft to get things working, and then we can sort out how we want to actually organize everything afterward. 

Perhaps the 3 of us can have a discussion on the best way to approach this?

**Comment by jacobvjk** [comment]
> I agree that we should avoid polluting `main.R` too much, but it's fine to get the logic in there while in draft to get things working, and then we can sort out how we want to actually organize everything afterward.
> 
> Perhaps the 3 of us can have a discussion on the best way to approach this?

yea, we had an initial discussion last week but now that the code is functional, I would appreciate a follow up for a decision. I want to deliver the p4b scenarios this sprint and while I have them prepared locally, I would feel better about using the final script for that.

**Comment by cjyetman** [comment]
I wasn't expecting it to require so much code. Might make sense to put it in a separate script source it, same as the separate scenario scripts.

**Review by jdhoffa — APPROVED** [review]

**Comment by jdhoffa** [comment]
lookth good

**Review by cjyetman — APPROVED** [review]
a bit of a rubber stamp on the changes made since I last reviewed this, but I trust this works

**Pull request merged**
