### PR TITLE
build(docker): Use core RMI workflow

### PR DESCRIPTION
**Pull request by AlexAxthelm**
Use a branch workflow to build the docker image now that it supports specifying platforms

Closes: #45

### CODE REVIEW

**Comment by AlexAxthelm** [comment]
Depends on https://github.com/RMI-PACTA/actions/pull/77

**Review by cjyetman — CHANGES_REQUESTED** [review]
Please move changes to the Docker file to a separate PR with appropriate documentation of the reasoning for them.

**Comment by AlexAxthelm** [comment]
The changes to the docker file are relevant to this PR, since they are needed to pass the check system dependencies check.

**Comment by cjyetman** [comment]
I'd rather not install specific versions of system software and instead let that be determined by the most up-to-date information for the installed versions of the R packages that depend on them.

**Comment by cjyetman** [comment]
I disagree

**Comment by cjyetman** [comment]
superseded by #52

**Pull request closed without merging**
